# Generated by Django 5.1.1 on 2024-10-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('name', models.CharField(max_length=100, verbose_name='Название логотипа')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
