# Generated by Django 5.1.1 on 2024-10-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesetting_delete_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='popup_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
