# Generated by Django 5.1.1 on 2024-10-08 18:48

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('invite_until', models.DateField(default=django.utils.timezone.now, verbose_name='Invite until')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Post')),
                ('title', models.CharField(max_length=100, verbose_name='Post name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('short_content', models.TextField(verbose_name='Short description')),
                ('full_content', ckeditor.fields.RichTextField(verbose_name='Full post content')),
                ('file', models.FileField(blank=True, upload_to='posts/files', verbose_name='Terms and agreements')),
                ('image_logo', models.ImageField(blank=True, null=True, upload_to='posts/images', verbose_name='Logo')),
                ('image_big', models.ImageField(blank=True, null=True, upload_to='posts/images', verbose_name='Image upload - big')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Post date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Post date updated')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Social Network Name')),
                ('url', models.URLField(verbose_name='Social Network URL')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/images', verbose_name='Image upload')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='social_networks',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.socialnetwork'),
        ),
    ]
