# Generated by Django 5.1.1 on 2024-10-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Logo Name')),
                ('image', models.ImageField(upload_to='logos/', verbose_name='Logo Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_logo',
        ),
        migrations.AddField(
            model_name='post',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.logo'),
        ),
    ]
